export interface Invoice {
    ID: number;
    ShipAddress: string;
    ShipCity: string;
    ShipCountry: string;
    ShipName: string;
    ShipRegion: string;
    ShipPostalCode: string;
    CustomerID: string;
    CustomerName: string;
    Address: string;
    City: string;
    Region: string;
    PostalCode: string;
    Country: string;
    Salesperson: string;
    OrderID: number;
    OrderDate: Date;
    ShipperName: string;
    ProductID: number;
    ProductName: string;
    UnitPrice: number;
    Quantity: number;
    Discontinued: boolean;
    ExtendedPrice: number;
    Freight: number;
}

export const INVOICE_DATA = [{
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipCountry: "Germany",
    ShipName: "Alfred's Futterkiste",
    ShipRegion: null,
    ShipPostalCode: "12209",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Margaret Peacock",
    OrderID: 10692,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "United Package",
    ProductID: 63,
    ProductName: "Vegie-spread",
    UnitPrice: 43.9000,
    Quantity: 20,
    Discontinued: false,
    ExtendedPrice: 878.0000,
    Freight: 61.0200
}, {
    ShipName: "Alfred's Futterkiste",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Margaret Peacock",
    OrderID: 10702,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 3,
    ProductName: "Aniseed Syrup",
    UnitPrice: 10.0000,
    Quantity: 6,
    Discontinued: false,
    ExtendedPrice: 60.0000,
    Freight: 23.9400
}, {
    ShipName: "Alfred's Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Margaret Peacock",
    OrderID: 10702,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 76,
    ProductName: "Lakkalik\u00f6\u00f6ri",
    UnitPrice: 18.0000,
    Quantity: 15,
    Discontinued: false,
    ExtendedPrice: 270.0000,
    Freight: 23.9400
}, {
    ShipName: "Alfred's Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Nancy Davolio",
    OrderID: 10835,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Federal Shipping",
    ProductID: 59,
    ProductName: "Raclette Courdavault",
    UnitPrice: 55.0000,
    Quantity: 15,
    Discontinued: false,
    ExtendedPrice: 825.0000,
    Freight: 69.5300
}, {
    ShipName: "Alfred's Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Nancy Davolio",
    OrderID: 10952,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 28,
    ProductName: "R\u00f6ssle Sauerkraut",
    UnitPrice: 45.6000,
    Quantity: 2,
    Discontinued:  true,
    ExtendedPrice: 91.2000,
    Freight: 40.4200
}, {
    ShipName: "Alfred's Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Janet Leverling",
    OrderID: 11011,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 71,
    ProductName: "Flotemysost",
    UnitPrice: 21.5000,
    Quantity: 20,
    Discontinued:  true,
    ExtendedPrice: 430.0000,
    Freight: 1.2100
}, {
    ShipName: "Alfred's Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Nancy Davolio",
    OrderID: 10952,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 6,
    ProductName: "Grandma's Boysenberry Spread",
    UnitPrice: 25.0000,
    Quantity: 16,
    Discontinued: true,
    ExtendedPrice: 380.0000,
    Freight: 40.4200
}, {
    ShipName: "Alfred's Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Janet Leverling",
    OrderID: 11011,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 58,
    ProductName: "Escargots de Bourgogne",
    UnitPrice: 13.2500,
    Quantity: 40,
    Discontinued: true,
    ExtendedPrice: 503.5000,
    Freight: 1.2100
}, {
    ShipName: "Alfred's Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Nancy Davolio",
    OrderID: 10835,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Federal Shipping",
    ProductID: 77,
    ProductName: "Original Frankfurter gr\u00fcne So\u00dfe",
    UnitPrice: 13.0000,
    Quantity: 2,
    Discontinued:  true,
    ExtendedPrice: 20.8000,
    Freight: 69.5300
}, {
    ShipName: "Alfreds Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Michael Suyama",
    OrderID: 10643,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 28,
    ProductName: "R\u00f6ssle Sauerkraut",
    UnitPrice: 45.6000,
    Quantity: 15,
    Discontinued:  true,
    ExtendedPrice: 513.0000,
    Freight: 29.4600
}, {
    ShipName: "Alfreds Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Michael Suyama",
    OrderID: 10643,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 39,
    ProductName: "Chartreuse verte",
    UnitPrice: 18.0000,
    Quantity: 21,
    Discontinued:  true,
    ExtendedPrice: 283.5000,
    Freight: 29.4600
}, {
    ShipName: "Alfreds Futterkiste",
    ShipAddress: "Obere Str. 57",
    ShipCity: "Berlin",
    ShipRegion: null,
    ShipPostalCode: "12209",
    ShipCountry: "Germany",
    CustomerID: "ALFKI",
    CustomerName: "Alfreds Futterkiste",
    Address: "Obere Str. 57",
    City: "Berlin",
    Region: null,
    PostalCode: "12209",
    Country: "Germany",
    Salesperson: "Michael Suyama",
    OrderID: 10643,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Speedy Express",
    ProductID: 46,
    ProductName: "Spegesild",
    UnitPrice: 12.0000,
    Quantity: 2,
    Discontinued: true,
    ExtendedPrice: 18.0000,
    Freight: 29.4600
}, {
    ShipName: "Ana Trujillo Emparedados y helados",
    ShipAddress: "Avda. de la Constituci\u00f3n 2222",
    ShipCity: "M\u00e9xico D.F.",
    ShipRegion: null,
    ShipPostalCode: "05021",
    ShipCountry: "Mexico",
    CustomerID: "ANATR",
    CustomerName: "Ana Trujillo Emparedados y helados",
    Address: "Avda. de la Constituci\u00f3n 2222",
    City: "M\u00e9xico D.F.",
    Region: null,
    PostalCode: "05021",
    Country: "Mexico",
    Salesperson: "Robert King",
    OrderID: 10308,
    OrderDate:  new Date("11/23/2016"),
    ShipperName: "Federal Shipping",
    ProductID: 69,
    ProductName: "Gudbrandsdalsost",
    UnitPrice: 28.8000,
    Quantity: 1,
    Discontinued: false,
    ExtendedPrice: 28.8000,
    Freight: 1.6100
}];